--- 
- name: Install necessary packages for unattended upgrades
  apt:
    name:
      - unattended-upgrades
      - apt-listchanges
      - apticron
    state: present
    update_cache: yes

- name: Create custom unattended-upgrades configuration
  template:
    src: 51myunattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/51myunattended-upgrades
    mode: '0644'
